// <auto-generated />
using System;
using Lagerverwaltungssystem3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lagerverwaltungssystem3.Migrations
{
    [DbContext(typeof(LagerverwaltungssystemContext))]
    [Migration("20210927065637_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Delivery", b =>
                {
                    b.Property<int>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Deliverydate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("DeliveryID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Deliveryposition", b =>
                {
                    b.Property<int>("DeliverypositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeliveryID")
                        .HasColumnType("int");

                    b.Property<int?>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("DeliverypositionID");

                    b.HasIndex("DeliveryID");

                    b.HasIndex("ItemID");

                    b.ToTable("Deliverypositions");
                });

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Avaliableamount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Orderdate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Orderposition", b =>
                {
                    b.Property<int>("OrderpositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemID")
                        .HasColumnType("int");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderpositionID");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("Orderpositions");
                });

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Delivery", b =>
                {
                    b.HasOne("Lagerverwaltungssystem2.Model.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Deliveryposition", b =>
                {
                    b.HasOne("Lagerverwaltungssystem2.Model.Delivery", "Delivery")
                        .WithMany("Deliverypositions")
                        .HasForeignKey("DeliveryID");

                    b.HasOne("Lagerverwaltungssystem2.Model.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID");

                    b.Navigation("Delivery");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Order", b =>
                {
                    b.HasOne("Lagerverwaltungssystem2.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Orderposition", b =>
                {
                    b.HasOne("Lagerverwaltungssystem2.Model.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID");

                    b.HasOne("Lagerverwaltungssystem2.Model.Order", "Order")
                        .WithMany("Orderpositions")
                        .HasForeignKey("OrderID");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Delivery", b =>
                {
                    b.Navigation("Deliverypositions");
                });

            modelBuilder.Entity("Lagerverwaltungssystem2.Model.Order", b =>
                {
                    b.Navigation("Orderpositions");
                });
#pragma warning restore 612, 618
        }
    }
}
