// <auto-generated />
using System;
using Lagerverwaltungssystem3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lagerverwaltungssystem3.Migrations
{
    [DbContext(typeof(LagerverwaltungssystemContext))]
    partial class LagerverwaltungssystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lagerverwaltungssystem3.Model.EntryExit", b =>
                {
                    b.Property<int>("EntryExitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryExitID");

                    b.ToTable("EntryExits");
                });

            modelBuilder.Entity("Lagerverwaltungssystem3.Model.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Avaliableamount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Lagerverwaltungssystem3.Model.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EntryExitID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Orderdate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderID");

                    b.HasIndex("EntryExitID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Lagerverwaltungssystem3.Model.Orderposition", b =>
                {
                    b.Property<int>("OrderpositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemID")
                        .HasColumnType("int");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderpositionID");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("Orderpositions");
                });

            modelBuilder.Entity("Lagerverwaltungssystem3.Model.Order", b =>
                {
                    b.HasOne("Lagerverwaltungssystem3.Model.EntryExit", "EntryExit")
                        .WithMany("Orders")
                        .HasForeignKey("EntryExitID");

                    b.Navigation("EntryExit");
                });

            modelBuilder.Entity("Lagerverwaltungssystem3.Model.Orderposition", b =>
                {
                    b.HasOne("Lagerverwaltungssystem3.Model.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID");

                    b.HasOne("Lagerverwaltungssystem3.Model.Order", "Order")
                        .WithMany("Orderpositions")
                        .HasForeignKey("OrderID");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Lagerverwaltungssystem3.Model.EntryExit", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Lagerverwaltungssystem3.Model.Order", b =>
                {
                    b.Navigation("Orderpositions");
                });
#pragma warning restore 612, 618
        }
    }
}
